### ISSUE TITLE
脚本运行的输入加入纠错功能

### ISSUE THREAD

**Issue by Wrandz** [sqkkyzx/plex_localization_zhcn#6]
### 如题，脚本交互运行时如果输入不是规定范围的输入，给出提示，并重新输入。现在是直接python报一堆错，虽然也行，但感觉应该可以更人性化一点。我对python不是很熟，没法PR了，大佬有兴趣的话烦请加一下哈哈。
```
(plexpinyin) root@plex:~/plex_localization_zhcn# python3 plex_localization_zhcn.py 
已成功连接到服务器plex

请输入运行的线程数（输入整数数字，默认为2）：

1> 电影 <movie>
2> 电视节目 <show>
请选择库：1^H2
Traceback (most recent call last):
  File "/root/plex_localization_zhcn/plex_localization_zhcn.py", line 252, in <module>
    PlexServer().loop_all()
  File "/root/plex_localization_zhcn/plex_localization_zhcn.py", line 232, in loop_all
    library_id, type_ids = self.select_library(library_id) if library_id else self.select_library()
  File "/root/plex_localization_zhcn/plex_localization_zhcn.py", line 130, in select_library
    index = index if index else int(input("\n" + "\n".join(echo) + "\n请选择库："))
ValueError: invalid literal for int() with base 10: '1\x082'
```

```
(plexpinyin) root@plex:~/plex_localization_zhcn# python3 plex_localization_zhcn.py 
已成功连接到服务器plex

请输入运行的线程数（输入整数数字，默认为2）：y^H^Hw
Traceback (most recent call last):
  File "/root/plex_localization_zhcn/plex_localization_zhcn.py", line 252, in <module>
    PlexServer().loop_all()
  File "/root/plex_localization_zhcn/plex_localization_zhcn.py", line 216, in loop_all
    thread_count = int(thread_count if thread_count else 2)
ValueError: invalid literal for int() with base 10: 'y\x08\x08w'
```

**Comment by sqkkyzx** [comment]
是一个可以优化的问题。
